### ISSUE TITLE
Design requirements

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/envisage-site#2]
The ideation doc can be found [here](https://docs.google.com/a/shaastra.org/document/d/1FQUT6WqTVQsK97W8Sp3O80UkE1FosVyeGWuANsXhBW0/edit?usp=sharing). I will also update content in the doc. But make sure it is done before 11 June, 9PM.

**Comment by TheOneCodeGuy** [comment]
What changes do you want me to make in the homepage? @gokulan97

**Comment by gokulan97** [comment]
Homepage will have Envisage Logo and what is Envisage. What I want both of you to do is create a doc on what is the structure of the site.

**Comment by navoditas** [comment]
@gokulan97 the envisage website requires just a login page and not a register page, right?

**Comment by gokulan97** [comment]
Yes. And the users can be seeded initially.

**Comment by TheOneCodeGuy** [comment]
I have given some ideas in the ideation document for fronte end animation. Can you please check it out?

**Comment by goku-kulan** [comment]
Cool. Add backend part also ASAP. Let me know if more people are needed to work on this.

**Comment by gokulan97** [comment]
Cool. Complete the backend part also ASAP. Also, let me know if more people are needed to work on the site.

**Comment by navoditas** [comment]
I thought the website ideation had to be frontend only...what do I have to
do for backend?

**Comment by TheOneCodeGuy** [comment]
Gokulan, I am facing a problem. I am not able to use any of the agularJS or angular 2 methods (ng-click/ (click) ). Can you please tell me how to use these methods?

**Comment by gokulan97** [comment]
Sorry got a bit busy. the client/app contains folder for every route. for eg. the main folder contains files related to the homepage (/). So, the JS file is main.component.js. Go through the export method present in it. It helps you understand better. Also, go through the CA Portal code in case if you face any difficulties. And still if you have any doubt, comment here. @Navs0806 you may also help him if needed.

**Comment by gokulan97** [comment]
design done. So closing this issue.
