### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/envisage-site#3]
Please push it at least once in two days so that I can track of what is happening. Also, @TheOneCodeGuy have you sorted out using AngularJS?

**Comment by TheOneCodeGuy** [comment]
No I am not getting it. Where do I add functions to be executed on click? How do I register the controllers? This framework is alien to me!

**Comment by TheOneCodeGuy** [comment]
Any angular framework I have used had views, scripts and styles folder with a js file doing the routing. I don't get how this one works. If you send me some resources, I will understand it faster and start working on it properly.

**Comment by gokulan97** [comment]
What is the status?

**Comment by gokulan97** [comment]
Closed.
