### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/envisage-site#4]
Few suggestions for the site:

The items on the Navigation Bar has to be visible even without users logging in.

**Comment by gokulan97** [comment]
@TheOneCodeGuy to be frank, I don't like the black there. Also, the animation on the navigation bar doesnt look good. Also, plan on where to put the envisage logo. I would suggest you follow Google Material design guidelines. Use colors from [here](https://material.io/guidelines/style/color.html).

@avinashselvam is our Frontend super coord. Get inputs from him for that. @avinashselvam add your suggestions for the site.

**Comment by TheOneCodeGuy** [comment]
Sure. I'll make it better. Just give me a day. I'll take input from avinash.

**Comment by gokulan97** [comment]
Nope, there isn't any time constraint for you. Take your time and work on it.

**Comment by gokulan97** [comment]
Indent the code @TheOneCodeGuy . Its too tough to read without that.

**Comment by navoditas** [comment]
@gokulan97 I am not getting how to get images from the user for the hidden portal. What should I use?

**Comment by gokulan97** [comment]
Did you mean image upload @TheOneCodeGuy ?

**Comment by navoditas** [comment]
Yes

**Comment by gokulan97** [comment]
Chuck it for now. Add all the needed images now to assets and make sure it works. Later we will implement  the file upload part. It has been already implemented in the CA Portal. So, in the last we will add it to the envisage site too.

**Comment by gokulan97** [comment]
@avinashselvam add your points on the design of the site here. Even if it is conveyed already, mention it here so that everyone knows about it.

**Comment by gokulan97** [comment]
Closed.
